version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./conf:/conf
      - ./data:/data
    ports:
      - 0.0.0.0:19953:53/udp
      - 0.0.0.0:18080:8080/tcp